### PR TITLE
[FORCE] Update funannotate_annotate

### PR DESCRIPTION
**Pull request by TomHarrop**
I think we're missing 2 revisions of this tool because the tests fail. I've tested this revision with planemo locally

### CODE REVIEW

**Comment by cat-bro** [comment]
I'll add this to a PR of recent failed tools

**Comment by cat-bro** [comment]
closed for #999

**Comment by TomHarrop** [comment]
@cat-bro I think that's an older revision

```
tools:
- name: funannotate_annotate
  owner: iuc
  revisions:
  - 756376aeb1ae
```

**Comment by cat-bro** [comment]
@TomHarrop oops!

**Review by cat-bro — APPROVED** [review]

**Pull request merged**
