### PR TITLE
Install request for single cell lab tools

### PR DESCRIPTION
**Pull request by neoformit**
I concatenated all the single cell sections into our one "Single-Cell" section.
This way I think we should be able to have them all installed to the base site as normal, but then split them into custom sections with a panel_view for the SC lab.

### CODE REVIEW

**Comment by cat-bro** [comment]
Don't worry about "Error: scanpy_plot revision 9a169729c9f9 is not installable" - that should be a warning because Galaxy will either install the next installable revision or skip because that revision is already installed.

Something like this: "Warning: Tool scanpy_run_umap revision ea91cfd0444e is already installed on https://staging.gvl.org.au/ in a different section 'HCA Single-cell'" needs to be fixed (should be an error)

**Comment by cat-bro** [comment]
I'll push some linter commits onto this

**Comment by neoformit** [comment]
Ok I'll filter out the ones that are already installed

**Comment by neoformit** [comment]
I made a little python script to remove tools that are already installed in a different section. Could that go in `scripts/` here?

**Comment by cat-bro** [comment]
that would be great

**Comment by neoformit** [comment]
Done @cat-bro

**Comment by cat-bro** [comment]
Thanks @neoformit . Not quite ready to merge this, thinking about adding container arrangements in tpv prior to merging.

**Comment by neoformit** [comment]
Let me know if I can do anything else

**Comment by cat-bro** [comment]
Thanks @neoformit. Could you please cut off everything below line 111 and paste it into another request? The installation process has been unpredictable so I'd like to see how it copes with the new release before giving it a bigger request.

**Comment by neoformit** [comment]
Sure, into a different file or different branch/PR?

**Comment by cat-bro** [comment]
different PR

**Comment by neoformit** [comment]
Done

**Review by cat-bro — APPROVED** [review]

**Pull request merged**
