### PR TITLE
Install bracken

### PR DESCRIPTION
**Pull request by neoformit**
Requested by Valentine @ QCIF
https://support.ehelp.edu.au/a/tickets/180122

### CODE REVIEW

**Review by igormakunin2 — APPROVED** [review]

**Review by igormakunin2 — APPROVED** [review]

**Comment by cat-bro** [comment]
Bracken needs reference data. GA has the data manager but I wasn't sure what kraken2 DBS to convert, the. I forgot about this. In the short term, we also need to consider how much space dbs will take up compared to what is available in /mnt/custom-indices.

**Comment by neoformit** [comment]
OK, worth waiting til the move to ETCA is done?

**Comment by mthang** [comment]
The pre-built databases of kraken2 and bracken are available on https://ccb.jhu.edu/software/bracken/ and the DBs size is listed here https://benlangmead.github.io/aws-indexes/k2 . Hopefully, it can give us some ideas how much diskspace is required.

**Comment by igormakunin2** [comment]
from Valentine:
I chatted with Mike before, the answer was I tried previously what was available but quite old db from 2021. We agreed to use the 2023 ones
[2:39](https://qfab.slack.com/archives/DKPD18132/p1695789549025829)

    StandardRefeq archaea, bacteria, viral, plasmid, human1, UniVec_Core6/5/2023

2 ..PlusPFStandard plus Refeq protozoa & fungi6/5/2023

IM: can we get downsampled versions of the databases?

**Comment by cat-bro** [comment]
bracken is installed now

**Pull request closed without merging**
